x-airflow-common: &airflow-common

  image: apache/airflow:3.2.2-python3.12

  env_file:
    - .env

  environment:

    AIRFLOW__CORE__EXECUTOR: LocalExecutor

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres_airflow:5432/${AIRFLOW_DB_NAME}"

    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

    AIRFLOW_CONN_POSTGRES_DWH: "postgresql://${DWH_USER}:${DWH_PASSWORD}@postgres_dwh:5432/${DWH_DATABASE}"

    AIRFLOW_VAR_DATA_DIR: ${DATA_DIR}
    AIRFLOW_VAR_BATCH_SIZE: ${BATCH_SIZE}
    AIRFLOW_VAR_UNKNOWN_CUSTOMER_ID: ${UNKNOWN_CUSTOMER_ID}
    AIRFLOW_VAR_DEFAULT_CATEGORY: ${DEFAULT_CATEGORY}
    AIRFLOW_VAR_DUPLICATE_STRATEGY: ${DUPLICATE_STRATEGY}

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data

  depends_on:
    postgres_airflow:
      condition: service_healthy

services:

  postgres_airflow:

    image: postgres:15

    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_dwh:

    image: postgres:15

    environment:
      POSTGRES_USER: ${DWH_USER}
      POSTGRES_PASSWORD: ${DWH_PASSWORD}
      POSTGRES_DB: ${DWH_DATABASE}

    volumes:
      - ./init_dwh:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DWH_USER} -d ${DWH_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:

    <<: *airflow-common

    command: >
      bash -c "
        airflow db migrate &&
        (airflow users create
          --username '${AIRFLOW_ADMIN_USER}'
          --password '${AIRFLOW_ADMIN_PASSWORD}'
          --role Admin
          --email '${AIRFLOW_ADMIN_EMAIL}'
          --firstname Sabin
          --lastname Areiza
        || echo 'Usuario ya existe, continuando...')
      "

    depends_on:
      postgres_airflow:
        condition: service_healthy
      postgres_dwh:
        condition: service_healthy

  airflow-apiserver:

    <<: *airflow-common

    command: api-server

    ports:
      - "8080:8080"

    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:

    <<: *airflow-common

    command: scheduler

    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:

    <<: *airflow-common

    command: dag-processor

    depends_on:
      airflow-init:
        condition: service_completed_successfully